(function () {
  function rowsToCsv(rows) {
    return rows
      .map((row) =>
        row
          .map((value) => {
            const text = String(value ?? "");
            return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
          })
          .join(",")
      )
      .join("\n");
  }

  function download(filename, content, type) {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  }

  function exportCsv(filename, headers, records) {
    download(filename, rowsToCsv([headers, ...records]), "text/csv;charset=utf-8");
  }

  function printPdf(title, html) {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`<!doctype html><html><head><title>${title}</title><style>
      body{font-family:Arial,sans-serif;margin:32px;color:#172033}
      table{width:100%;border-collapse:collapse;margin-top:16px}
      th,td{border:1px solid #d9e0ea;padding:8px;text-align:left}
      th{background:#eef3f8}
      .muted{color:#667085}
    </style></head><body><h1>${title}</h1><p class="muted">Generated by MAPPHEX Universal Report Engine</p>${html}</body></html>`);
    win.document.close();
    win.focus();
    win.print();
  }

  function tableHtml(headers, rows) {
    return `<table><thead><tr>${headers.map((header) => `<th>${header}</th>`).join("")}</tr></thead><tbody>${rows
      .map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`)
      .join("")}</tbody></table>`;
  }

  window.MapphexReports = {
    exportCsv,
    printPdf,
    tableHtml
  };
})();
